apiVersion: v1
data:
  GIT_SYNC_PASSWORD: WjJsMGFIVmlYM0JoZEY4eE1VRlFNMGxUTmxrd1ZVVjVWa2s1TkU5alNsVndYMlZsYWxsMFNraG1ZblZGZFZORlVXWlRRa3gwU0hvelpreHVPVWgyV1doQlpqUnpjakUyYWtGWmRXbFRUa2RCVmxnelUzRmtjbGxoUzB4UA==
  GIT_SYNC_USERNAME: ZEhKMWJteGxidz09
  GITSYNC_PASSWORD: WjJsMGFIVmlYM0JoZEY4eE1VRlFNMGxUTmxrd1ZVVjVWa2s1TkU5alNsVndYMlZsYWxsMFNraG1ZblZGZFZORlVXWlRRa3gwU0hvelpreHVPVWgyV1doQlpqUnpjakUyYWtGWmRXbFRUa2RCVmxnelUzRmtjbGxoUzB4UA==
  GITSYNC_USERNAME: ZEhKMWJteGxidz09
kind: Secret
metadata:
  creationTimestamp: "2025-11-23T13:59:00Z"
  name: git-credentials
  namespace: airflow
  resourceVersion: "800"
  uid: 2a46892c-7a7f-4076-a8ad-7d725e896a19
type: Opaque
